services:
  - type: web
    name: avadhoot/lcdiary
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /
    region: oregon
